# Generated by Django 3.0.7 on 2021-01-25 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_auto_20210115_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='examtype',
            name='exam_order',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='examtype',
            name='exam_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
