# Generated by Django 3.0.7 on 2021-02-11 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_auto_20210125_0237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examtype',
            options={'ordering': ['exam_order']},
        ),
    ]
