# # Generated by Django 3.0.7 on 2020-09-05 01:23

# from django.db import migrations


# class Migration(migrations.Migration):

#     dependencies = [
#         ('teachers', '0001_initial'),
#     ]

#     operations = [
#     ]

"""
Above one default code, below one written code
"""

from django.contrib.auth.models import Group, Permission
from django.db import models, migrations
from teachers.models import Teacher
import logging


logger = logging.getLogger(__name__)

# teacher_group_permissions = {
#   "Teacher Manager": [
#     "add_campaign",
#     "change_campaign",
#     "delete_campaign",
#     "view_campaign",
#     "add_campaignsms",
#     "add_sending",
#     "change_sending",
#     "view_sending"
#   ]
# }
headmaster_group_permissions = [
    "can_view_student",
    "can_view_teacher",
    "can_edit_teacher", 
    "can_view_headmaster",
]
perm = Permission.objects.get(name='Can add student')

def add_group_permissions(apps, schema_editor):

    group, created = Group.objects.get_or_create(name='Headmaster')   
    if created:
        group.permissions.add(
            perm,
            #can_view_teachers,
            #can_edit_teachers
        )
        logger.info('Headmaster Group created')

# def add_group_permissions():
#     # See https://code.djangoproject.com/ticket/23422
#     db_alias = schema_editor.connection.alias
#     try:
#         emit_post_migrate_signal(2, False, 'default')
#     except TypeError:  # Django < 1.8
#         emit_post_migrate_signal([], 2, False, 'default', db_alias)

#     for group in campaign_group_permissions:
#         role, created = Group.objects.get_or_create(name=group)
#         logger.info(f'{group} Group created')
#         for perm in campaign_group_permissions[group]:
#             role.permissions.add(Permission.objects.get(codename=perm))
#             logger.info(f'Permitting {group} to {perm}')
#         role.save()


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_group_permissions),
    ]