# Generated by Django 3.0.7 on 2021-02-08 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_auto_20210108_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='NID_no',
            field=models.CharField(max_length=100, null=True, verbose_name='NID no.:'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='date_of_join',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='fax',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='highest_educational_qualification',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='home_telephone',
            field=models.CharField(max_length=13, null=True, verbose_name='Telephone no.(Home)'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='marital_status',
            field=models.CharField(choices=[('MR', 'Married'), ('UM', 'Unmarried')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='office_mobile',
            field=models.CharField(max_length=11, null=True, verbose_name='Mobilephone no.(Office)'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='office_telephone',
            field=models.CharField(max_length=13, null=True, verbose_name='Telephone no.(Office)'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='permanent_address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='personal_mobile',
            field=models.CharField(max_length=11, null=True, verbose_name='Mobilephone no.(Personal)'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='present_address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='role',
            field=models.IntegerField(choices=[(1, 'Teacher'), (2, 'Class teacher'), (3, 'Headmaster')], null=True),
        ),
    ]
