# Generated by Django 3.0.7 on 2020-09-10 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_auto_20200905_0123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='designation',
        ),
    ]
