# Generated by Django 3.0.7 on 2021-02-11 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_auto_20210210_1847'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='role',
            field=models.IntegerField(choices=[(1, 'Teacher'), (2, 'Headmaster')], null=True),
        ),
    ]
