# Generated by Django 3.0.7 on 2021-01-08 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='notice_type',
            field=models.IntegerField(choices=[(0, 'General'), (1, 'Class Related')], default=0),
        ),
    ]
