# Generated by Django 3.0.7 on 2021-02-04 01:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(2021), django.core.validators.MaxValueValidator(2022)])),
            ],
        ),
    ]
