# Generated by Django 3.0.7 on 2020-12-26 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_auto_20201224_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='syllebus',
            field=models.FileField(null=True, upload_to='uploads/%Y/%m/'),
        ),
    ]
