# Generated by Django 3.0.7 on 2021-01-04 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        ('classes', '0002_auto_20201228_1016'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MarksSheet',
            new_name='MarkSheet',
        ),
    ]
