# Generated by Django 3.0.7 on 2020-09-09 13:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        ('teachers', '0002_auto_20200905_0123'),
        ('classes', '0002_class_class_teacher_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_year',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AddField(
            model_name='subject',
            name='teacher_name',
            field=models.ForeignKey(blank=True, choices=[('abc', 'abc')], null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.Teacher'),
        ),
        migrations.AlterField(
            model_name='class',
            name='class_teacher_username',
            field=models.OneToOneField(blank=True, choices=[('abc', 'abc')], null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.Teacher'),
        ),
        migrations.CreateModel(
            name='MarksSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjective_marks', models.IntegerField()),
                ('objective_marks', models.IntegerField()),
                ('total_marks', models.IntegerField()),
                ('letter_grade', models.CharField(max_length=5)),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.Exam')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student')),
            ],
        ),
    ]
