# Generated by Django 3.0.7 on 2021-01-08 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_auto_20210107_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='syllebus',
            field=models.FileField(max_length=200, null=True, upload_to='uploads/syllebus/%Y/%m/%d'),
        ),
    ]
