# Generated by Django 3.0.7 on 2021-01-08 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_auto_20210108_1240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name_plural': 'Classes'},
        ),
    ]
