# Generated by Django 3.0.7 on 2020-12-26 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_class_syllebus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='syllebus',
            field=models.FileField(max_length=200, null=True, upload_to='uploads/%Y/%m/'),
        ),
    ]
