# Generated by Django 3.0.7 on 2020-09-10 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_auto_20200909_1325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='class_teacher_username',
            new_name='class_teacher',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='teacher_name',
            new_name='teacher',
        ),
        migrations.AddField(
            model_name='markssheet',
            name='subject_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.Subject'),
        ),
    ]
