# Generated by Django 3.0.7 on 2021-01-12 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_auto_20210108_1301'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MarkSheet',
        ),
    ]
