# Generated by Django 3.0.7 on 2020-09-10 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_exam_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='subject',
        ),
    ]
