# Generated by Django 3.0.7 on 2021-01-15 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_delete_marksheet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='exam',
            new_name='exam_type',
        ),
    ]
