# Generated by Django 3.0.7 on 2021-01-25 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_auto_20210115_0127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name', 'status']},
        ),
        migrations.RemoveField(
            model_name='exam',
            name='objective_marks',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='objective_pass_marks',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='subjective_marks',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='subjective_pass_marks',
        ),
        migrations.AddField(
            model_name='exam',
            name='class_test_marks',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='term_objective_marks',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='term_objective_pass_marks',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='term_subjective_marks',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='term_subjective_pass_marks',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='term_total_conversion',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Term test total marks conversion(in %)'),
        ),
        migrations.AddField(
            model_name='subject',
            name='status',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')], default=0),
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_type',
            field=models.IntegerField(choices=[(0, 'Main'), (1, 'Optional')], null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='total_marks',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='total_pass_marks',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
