# Generated by Django 3.0.7 on 2021-01-28 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_auto_20210125_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_order',
            field=models.IntegerField(null=True),
        ),
    ]
