# Generated by Django 3.0.7 on 2020-09-10 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_remove_markssheet_exam_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='class_teacher',
        ),
        migrations.RemoveField(
            model_name='markssheet',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='markssheet',
            name='subject_id',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='teacher',
        ),
    ]
