# Generated by Django 3.0.7 on 2021-01-28 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0008_class_class_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='syllebus',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to='uploads/syllebus/%Y/%m/%d'),
        ),
    ]
