# Generated by Django 3.0.7 on 2021-01-31 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0009_auto_20210128_0340'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='lab_marks',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='lab_pass_marks',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
