# Generated by Django 3.0.7 on 2020-09-10 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        ('classes', '0009_auto_20200910_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='markssheet',
            name='exam_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.Exam'),
        ),
        migrations.AddField(
            model_name='markssheet',
            name='student_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.Student'),
        ),
        migrations.AddField(
            model_name='markssheet',
            name='subject_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.Subject'),
        ),
    ]
