# Generated by Django 3.0.7 on 2021-02-01 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0010_auto_20210131_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='total_marks',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='total_pass_marks',
        ),
    ]
