# Generated by Django 3.0.7 on 2020-09-12 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0011_exam_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='markssheet',
            name='exam_id',
        ),
        migrations.RemoveField(
            model_name='markssheet',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='markssheet',
            name='subject_id',
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
        migrations.DeleteModel(
            name='MarksSheet',
        ),
    ]
