# Generated by Django 3.0.7 on 2020-09-12 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0012_auto_20200912_0137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='class_id',
            new_name='related_class',
        ),
    ]
