# Generated by Django 3.0.7 on 2020-09-12 01:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        ('classes', '0013_auto_20200912_0142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=50)),
                ('exam_year', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(9999)])),
                ('subjective_marks', models.IntegerField()),
                ('objective_marks', models.IntegerField()),
                ('total_marks', models.IntegerField()),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.Class')),
                ('subject', models.ForeignKey(blank=True, choices=[(2, 'English')], null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='MarksSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjective_marks', models.IntegerField()),
                ('objective_marks', models.IntegerField()),
                ('total_marks', models.IntegerField()),
                ('letter_grade', models.CharField(max_length=5)),
                ('exam_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.Exam')),
                ('student_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.Student')),
                ('subject_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.Subject')),
            ],
        ),
    ]
