# Generated by Django 3.0.7 on 2021-02-04 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0013_auto_20210204_0619'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['status', 'name']},
        ),
    ]
