# Generated by Django 3.0.7 on 2021-02-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0015_routine'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='period',
            field=models.IntegerField(null=True),
        ),
    ]
