# Generated by Django 3.0.7 on 2020-09-13 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0015_auto_20200912_0227'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
