# Generated by Django 3.0.7 on 2020-09-14 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_teacher_designation'),
        ('classes', '0016_delete_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_teacher',
            field=models.OneToOneField(blank=True, choices=[('abc', 'abc'), ('hhhh', 'hhhh jjjjj')], null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.Teacher'),
        ),
    ]
