# Generated by Django 3.0.7 on 2021-02-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0016_routine_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='total_class_in_a_day',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='total_class_in_a_week',
            field=models.IntegerField(null=True),
        ),
    ]
