# Generated by Django 3.0.7 on 2021-02-08 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0017_auto_20210206_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routine',
            name='wednesay',
        ),
        migrations.AddField(
            model_name='routine',
            name='wednesday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wednesday', to='classes.Subject'),
        ),
        migrations.AlterField(
            model_name='routine',
            name='monday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monday', to='classes.Subject'),
        ),
        migrations.AlterField(
            model_name='routine',
            name='sunday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sunday', to='classes.Subject'),
        ),
        migrations.AlterField(
            model_name='routine',
            name='thursday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thursday', to='classes.Subject'),
        ),
        migrations.AlterField(
            model_name='routine',
            name='tuesday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tuesday', to='classes.Subject'),
        ),
    ]
