# Generated by Django 3.0.7 on 2021-02-08 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0018_auto_20210208_0454'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='saturday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saturday', to='classes.Subject'),
        ),
    ]
