# Generated by Django 3.0.7 on 2020-09-20 02:04

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.comparison


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0020_auto_20200920_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='subject',
            field=models.ForeignKey(blank=True, limit_choices_to={'related_class': django.db.models.functions.comparison.Cast('related_class', output_field=models.IntegerField())}, null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.Subject'),
        ),
    ]
