# Generated by Django 3.0.7 on 2021-02-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0020_class_board_exam_evaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='total_students',
            field=models.IntegerField(null=True),
        ),
    ]
