# Generated by Django 3.0.7 on 2021-02-11 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0021_class_total_students'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['class_order'], 'verbose_name_plural': 'Classes'},
        ),
    ]
