# Generated by Django 3.0.7 on 2020-09-20 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0024_auto_20200920_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='group',
            field=models.CharField(blank=True, choices=[('Sci', 'Science'), ('Hum', 'Humanities'), ('Bus', 'Business Studies')], max_length=30, null=True),
        ),
    ]
