# Generated by Django 3.0.7 on 2020-09-20 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0029_auto_20200920_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='subject',
            field=models.ForeignKey(blank=True, limit_choices_to={'related_class_id': models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.Class')}, null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.Subject'),
        ),
    ]
