# Generated by Django 3.0.7 on 2020-09-22 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0031_auto_20200922_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='subject',
            field=models.ForeignKey(blank=True, limit_choices_to={'related_class_id': 9}, null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.Subject'),
        ),
    ]
