# Generated by Django 3.0.7 on 2020-09-26 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
        ('classes', '0037_auto_20200924_0114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='exam_name',
        ),
        migrations.AddField(
            model_name='exam',
            name='exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.Exam'),
        ),
    ]
