# Generated by Django 3.0.7 on 2020-09-30 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0038_auto_20200926_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='objective_pass_marks',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='objective pass marks (in %)'),
        ),
        migrations.AddField(
            model_name='exam',
            name='subjective_pass_marks',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='subjective pass marks (in %)'),
        ),
        migrations.AddField(
            model_name='exam',
            name='total_pass_marks',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='total pass marks (in %)'),
        ),
        migrations.AlterField(
            model_name='markssheet',
            name='objective_marks',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='markssheet',
            name='subjective_marks',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='markssheet',
            name='total_marks',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
