# Generated by Django 3.0.7 on 2021-01-08 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='about_us_photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/others/%Y/%m/%d/', verbose_name='About Us Page Photo'),
        ),
        migrations.AddField(
            model_name='institution',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='headmaster_photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/others/%Y/%m/%d/', verbose_name="Headmaster's Photo"),
        ),
        migrations.AddField(
            model_name='institution',
            name='headmaster_speech',
            field=models.TextField(blank=True, null=True, verbose_name="Headmaster's Speech"),
        ),
        migrations.AddField(
            model_name='institution',
            name='phone_no',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Phone No.(Office)'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='academic_photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/others/%Y/%m/%d/', verbose_name='Academic Page Photo'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='home_background',
            field=models.ImageField(blank=True, null=True, upload_to='photos/others/%Y/%m/%d/', verbose_name='Homepage Background Photo'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='home_photo_1',
            field=models.ImageField(blank=True, null=True, upload_to='photos/others/%Y/%m/%d/', verbose_name='Homepage Photo 1'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='home_photo_2',
            field=models.ImageField(blank=True, null=True, upload_to='photos/others/%Y/%m/%d/', verbose_name='Homepage Photo 1'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='home_photo_3',
            field=models.ImageField(blank=True, null=True, upload_to='photos/others/%Y/%m/%d/', verbose_name='Homepage Photo 1'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='home_photo_4',
            field=models.ImageField(blank=True, null=True, upload_to='photos/others/%Y/%m/%d/', verbose_name='Homepage Photo 1'),
        ),
        migrations.CreateModel(
            name='EventNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateField(null=True)),
                ('title', models.CharField(max_length=250, null=True)),
                ('description', models.TextField(null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/others/%Y/%m/%d/', verbose_name='Attached Photo')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.Institution')),
            ],
        ),
    ]
