# Generated by Django 3.0.7 on 2021-01-04 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='academic_photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/others/%Y/%m/%d/', verbose_name='Academic page photo'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='home_background',
            field=models.ImageField(blank=True, null=True, upload_to='photos/others/%Y/%m/%d/', verbose_name='Homepage background photo'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='home_photo_1',
            field=models.ImageField(blank=True, null=True, upload_to='photos/others/%Y/%m/%d/', verbose_name='Homepage photo 1'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='home_photo_2',
            field=models.ImageField(blank=True, null=True, upload_to='photos/others/%Y/%m/%d/', verbose_name='Homepage photo 1'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='home_photo_3',
            field=models.ImageField(blank=True, null=True, upload_to='photos/others/%Y/%m/%d/', verbose_name='Homepage photo 1'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='home_photo_4',
            field=models.ImageField(blank=True, null=True, upload_to='photos/others/%Y/%m/%d/', verbose_name='Homepage photo 1'),
        ),
    ]
