# Generated by Django 3.0.7 on 2021-01-08 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0002_auto_20210108_1115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventnews',
            old_name='date_time',
            new_name='date',
        ),
    ]
