# Generated by Django 3.0.7 on 2020-09-13 02:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0016_delete_subject'),
        ('teachers', '0004_teacher_designation'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=50)),
                ('exam_year', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(9999)])),
                ('subjective_marks', models.IntegerField()),
                ('objective_marks', models.IntegerField()),
                ('total_marks', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('related_class', models.ForeignKey(choices=[(2, '10')], null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.Class')),
                ('teacher', models.ForeignKey(blank=True, choices=[('abc', 'abc')], null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='MarksSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjective_marks', models.IntegerField()),
                ('objective_marks', models.IntegerField()),
                ('total_marks', models.IntegerField()),
                ('letter_grade', models.CharField(max_length=5)),
                ('exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subjects_and_exams.Exam')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.Student')),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects_and_exams.Subject'),
        ),
    ]
