# Generated by Django 3.0.7 on 2020-09-13 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0016_delete_subject'),
        ('subjects_and_exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='related_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.Class'),
        ),
    ]
