# Generated by Django 3.0.7 on 2020-09-13 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_teacher_designation'),
        ('subjects_and_exams', '0003_auto_20200913_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='class_name',
            field=models.CharField(choices=[(2, '10')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='teacher_name',
            field=models.CharField(blank=True, choices=[('abc', 'abc')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.Teacher'),
        ),
    ]
