# Generated by Django 3.0.7 on 2020-09-14 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects_and_exams', '0005_auto_20200913_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='class_name',
            field=models.IntegerField(choices=[(2, '10'), (3, 'Nine (Science)')], null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='teacher_name',
            field=models.CharField(blank=True, choices=[('abc', 'abc'), ('hhhh', 'hhhh jjjjj')], max_length=30, null=True),
        ),
    ]
