# Generated by Django 3.0.7 on 2020-09-14 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects_and_exams', '0006_auto_20200914_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='class_name',
            field=models.IntegerField(choices=[(2, '10'), (3, 'Nine (Science)'), (4, 'Nine (Business)')], null=True),
        ),
    ]
