# Generated by Django 3.0.7 on 2020-06-15 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('username', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('duplicate_name_count', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=30)),
                ('mother_name', models.CharField(max_length=100, verbose_name="Mother's name")),
                ('father_name', models.CharField(max_length=100, verbose_name="Father's name")),
                ('guardian_name', models.CharField(max_length=100, verbose_name="Guardian's name(applicaple if different from parents)")),
                ('present_address', models.TextField()),
                ('permanent_address', models.TextField()),
                ('email', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=11, verbose_name='Telephone no.')),
                ('emergency_telephone', models.CharField(max_length=11, verbose_name='Emergency telephone No.')),
                ('religion', models.CharField(max_length=30)),
                ('nationality', models.CharField(max_length=30)),
                ('previous_class', models.IntegerField()),
                ('previous_school', models.CharField(max_length=40)),
                ('current_class', models.CharField(choices=[('0', 'Nursery'), ('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('5', 'Five'), ('6', 'Six'), ('7', 'Seven'), ('8', 'Eight'), ('9', 'Nine'), ('10', 'Ten')], max_length=2)),
                ('tc_number', models.CharField(max_length=50, verbose_name='T.C no.')),
                ('date', models.DateField()),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('employed_guardian_name', models.CharField(max_length=50, verbose_name="Father/Mother's name")),
                ('student_signature', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name="Student's signature")),
                ('guardian_signature', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name="Guardian's signature")),
                ('headmaster_signature', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name="Headmaster/Principal's signature")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
