# Generated by Django 3.0.7 on 2020-09-14 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='current_class',
            field=models.CharField(choices=[(2, '10')], max_length=2),
        ),
    ]
