# Generated by Django 3.0.7 on 2021-01-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20210108_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='roll_no',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
