# Generated by Django 3.0.7 on 2020-09-14 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20200914_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='current_class',
            field=models.IntegerField(choices=[(2, '10'), (3, 'Nine (Science)')]),
        ),
    ]
