# Generated by Django 3.0.7 on 2020-09-14 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20200914_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='current_class',
            field=models.IntegerField(choices=[(2, '10'), (3, 'Nine (Science)'), (4, 'Nine (Business)')]),
        ),
    ]
