# Generated by Django 3.0.7 on 2021-01-28 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_roll_no'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['roll_no']},
        ),
    ]
