# Generated by Django 3.0.7 on 2021-02-08 14:16

from django.db import migrations, models
import students.models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20210128_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.PositiveIntegerField(default=students.models.get_roll),
        ),
    ]
