# Generated by Django 3.0.7 on 2020-09-19 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0017_auto_20200914_0302'),
        ('students', '0005_auto_20200914_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='current_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.Class'),
        ),
    ]
