# Generated by Django 3.0.7 on 2021-02-11 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20210208_1416'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['roll_no', 'current_class']},
        ),
    ]
