# Generated by Django 3.0.7 on 2020-09-25 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_auto_20200920_0059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='duplicate_name_count',
        ),
    ]
